language: rust
sudo: false
cache: cargo
rust:
  - nightly-2018-04-19
  - beta
  - stable

env:
  global:
    - CLIPPY_VERSION=0.0.195
    - secure: "pVJavkcBAUPuTH+7PY1eTzsfN6JD7CFbe7wDTgiIOfDjxbe1g6RnS/BQyUkNjoPORUf2rykBEeRJ7v2UIkBeOvqTCjjXbNUPEdMWjmkNGa3VJOZPaI3aTjQevhnKfc41fQyyY0hF1TijkryFUDSnoYQ66nWRlEdLcSGAfQmNc2r3ViaxOeSZtTKfeYYDTCT78d2xf21e6NMb+srkviAEyYmsJtg6VR7ilxDdXO9kafyrId4K0Fo3sc48fMuXZNfCtJLH/RNiSB05X0VYhdg/7GfXqHJXizcDdTpPngddSFPaolY3iIFfYOXQyLTuwoV2YKIM9O50Qzo4QwNnvK0s0xE2t07X1iQLTHax+30Jor+zw38ZRI3ExlqG0sFcCIlOtOa38dTnFqDX0EqehOkhKUMWHD/pEreqkfzU9FY6l6Klz6NccvH+84d+6klHvWjHYbHgGBEeLaZESBbaIf4Hepy6RhHqKo3G2bbiNLfztL50saLfaFNLUtat1E5Ntju/AN5a7hZgQFSkDgLGSDx4KhmRyZppHnnzuHUvjLqwLyF6JrHOnxgpu+HCF9P0iJY5bLmaIplL5pwPDE/ssDq3KWh+SAbYRrSsfhDdAE47pfuxiv1RiN7IbjnkcpEx0M7i7/3vmX0GRP2Q9Q1DFyJZ6suvTLJaVvE4I5HngHKLu/M="

before_script:
  - case "$TRAVIS_RUST_VERSION" in nightly*)
      cargo install clippy --vers $CLIPPY_VERSION --force;
    esac

script:
  - cargo test
  - case "$TRAVIS_RUST_VERSION" in nightly*)
      cargo clippy -- -D warnings;
    esac

before_deploy:
  - cargo package

deploy:
  provider: script
  script: cargo publish --verbose --token "$CRATES_IO_TOKEN"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    condition: "$TRAVIS_RUST_VERSION = stable"
